### ISSUE TITLE
Проблема описания свойств

### ISSUE THREAD

**Issue by vladflotsky** [nekodevone/nwapi-plugins#1]
Практические все классы имеют описание своих свойств. Прикол лишь в том, что в этом нет смысла. Допустим, возьмем структура Report.

`/// <summary>`
`/// Причина`
`/// </summary>`
`public string Reason { get; set; }`
Если перевести слово `Reason`, то можно понять, что это причина. Также и с описаниями конфига. В большинство случаях само название говорит о том, за что отвечает свойство. Писать такие summary - пустая трата времени

**Comment by Remuchi** [comment]
ok

**Comment by Nekonyx** [comment]
Комменты к коду — это хорошо. А чем их больше — тем лучше.
